const API_BASE_URL = process.env.NEXT_PUBLIC_API_BASE_URL ?? "http://localhost:8000";

export type WaitingForInput = {
  status: "waiting_for_input";
  thread_id: string;
  message: string;
  questions: string[];
};

/** Covers both a finished run (`state` populated) and a failed one (`message` populated instead). */
export type RunComplete = {
  status: string;
  thread_id: string;
  state?: Record<string, unknown>;
  message?: string;
};

export type DesignRunResponse = WaitingForInput | RunComplete;

export function isWaitingForInput(res: DesignRunResponse): res is WaitingForInput {
  return res.status === "waiting_for_input";
}

async function postJson<T>(path: string, body: unknown): Promise<T> {
  let res: Response;
  try {
    res = await fetch(`${API_BASE_URL}${path}`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(body),
    });
  } catch {
    throw new Error(`Could not reach the backend at ${API_BASE_URL} — is it running?`);
  }

  if (!res.ok) {
    let detail = res.statusText;
    try {
      const data = await res.json();
      detail = data.detail ?? JSON.stringify(data);
    } catch {
      // response wasn't JSON — fall back to statusText
    }
    throw new Error(`${res.status}: ${detail}`);
  }

  return res.json() as Promise<T>;
}

/**
 * Kicks off a new design run for the given product prompt.
 * `threadId` should be generated by the caller (crypto.randomUUID()) so the
 * run's progress stream can be opened before/while this resolves.
 */
export function startDesign(userQuery: string, threadId: string): Promise<DesignRunResponse> {
  return postJson<DesignRunResponse>("/design/start", { user_query: userQuery, thread_id: threadId });
}

/** Resumes a paused run with the user's answers, keyed by question text. */
export function resumeDesign(threadId: string, answers: Record<string, string>): Promise<DesignRunResponse> {
  return postJson<DesignRunResponse>("/design/resume", { thread_id: threadId, answers });
}

export type RunStreamEvent =
  | { type: "node_start"; node: string }
  | { type: "node_end"; node: string }
  | ({ type: "terminal" } & DesignRunResponse);

/**
 * Opens a live SSE connection to a run's progress. Returns the EventSource
 * so the caller can close() it (e.g. on unmount) — the connection is also
 * closed automatically once a "terminal" event arrives.
 */
export function openRunStream(
  threadId: string,
  handlers: {
    onNodeStart?: (node: string) => void;
    onNodeEnd?: (node: string) => void;
    onTerminal?: (res: DesignRunResponse) => void;
    onError?: () => void;
  }
): EventSource {
  const source = new EventSource(`${API_BASE_URL}/design/stream/${threadId}`);

  source.onmessage = (msg) => {
    let event: RunStreamEvent;
    try {
      event = JSON.parse(msg.data);
    } catch {
      return;
    }
    if (event.type === "node_start") handlers.onNodeStart?.(event.node);
    else if (event.type === "node_end") handlers.onNodeEnd?.(event.node);
    else if (event.type === "terminal") {
      handlers.onTerminal?.(event);
      source.close();
    }
  };

  source.onerror = () => {
    handlers.onError?.();
  };

  return source;
}
